### ISSUE TITLE
Use GraphQL to make frontend dev happy

### ISSUE THREAD

**Issue by subesokun** [anoff/cryptobooks#7]
For the frontend API we should use GraphQL and connect the resolvers to the Azure storage.

**Comment by anoff** [comment]
I'd use graphQL for interacting with the pricing API and REST to _save_/_load_ the user assets, which should happen only once for a session. Agree?

**Comment by subesokun** [comment]
Mhh personally I'd use it for both and depending and the current view only a subset of the user assets might be loaded to improve the initial page load, especially on flaky networks. But as I don't know yet which data gets transferred when loading the user assets I can't say that for sure. Also maintaining and documentating two APIs might be a bit troublesome.

**Comment by anoff** [comment]
🚮
